on:
  workflow_dispatch: {}
jobs:
  build_intel_mac_app:
    runs-on: macos-12
    steps:
    - env:
        EXAMPLE_TOKEN: my-token
      run: |-
        echo "hello gh action 2"
        echo "hello gh action 3"