on:
  workflow_dispatch: {}
jobs:
  build_intel_mac_app:
    runs-on: macos-12
    steps:
    - !<matt.mbuild.admin.ghwf.model.action.GHUseAction>
      uses: robinraju/release-downloader@v1.7
      with:
        repository: mjgroth/deephys
        latest: true
        fileName: nn-deephys-intel-0-all.jar
    - !<matt.mbuild.admin.ghwf.model.action.GHRunAction>
      env:
        EXAMPLE_TOKEN: my-token
      run: "\t\t\t  echo hello gh action 2\necho hello gh action 3\nls\njpackage --type\
        \ app-image --verbose --name deephys --app-version 1.26.0 --java-options -Dprism.maxvram=2G\
        \ --java-options -Xmx6144m --java-options -XX:-OmitStackTraceInFastThrow --dest\
        \ . --icon logo.icns --input input --temp temp [Ljava.lang.String;@71159560"
  build_linux_app:
    runs-on: ubuntu-22.04
    steps:
    - !<matt.mbuild.admin.ghwf.model.action.GHUseAction>
      uses: robinraju/release-downloader@v1.7
      with:
        repository: mjgroth/deephys
        latest: true
        fileName: nn-deephys-linux-0-all.jar
    - !<matt.mbuild.admin.ghwf.model.action.GHRunAction>
      env:
        EXAMPLE_TOKEN: my-token
      run: "\t\t\t  echo hello gh action 2\necho hello gh action 3\nls\njpackage --type\
        \ app-image --verbose --name deephys --app-version 1.26.0 --java-options -Dprism.maxvram=2G\
        \ --java-options -Xmx6144m --java-options -XX:-OmitStackTraceInFastThrow --dest\
        \ . --icon logo.icns --input input --temp temp [Ljava.lang.String;@14e5ba86"
  build_windows_app:
    runs-on: windows-2022
    steps:
    - !<matt.mbuild.admin.ghwf.model.action.GHUseAction>
      uses: robinraju/release-downloader@v1.7
      with:
        repository: mjgroth/deephys
        latest: true
        fileName: nn-deephys-windows-0-all.jar
    - !<matt.mbuild.admin.ghwf.model.action.GHRunAction>
      env:
        EXAMPLE_TOKEN: my-token
      run: "\t\t\t  echo hello gh action 2\necho hello gh action 3\nls\njpackage --type\
        \ app-image --verbose --name deephys --app-version 1.26.0 --java-options -Dprism.maxvram=2G\
        \ --java-options -Xmx6144m --java-options -XX:-OmitStackTraceInFastThrow --dest\
        \ . --icon logo.icns --input input --temp temp [Ljava.lang.String;@3ab7ac49"