on:
  workflow_dispatch: {}
jobs:
  build_intel_mac_app:
    runs-on: macos-12
    steps:
    - !<matt.mbuild.admin.ghwf.model.GHUseAction>
      uses: robinraju/release-downloader@v1.7
      with:
        repository: mjgroth/deephys
        latest: true
        fileName: todo
    - !<matt.mbuild.admin.ghwf.model.GHRunAction>
      env:
        EXAMPLE_TOKEN: my-token
      run: |-
        echo "hello gh action 2"
        echo "hello gh action 3"