on:
  workflow_dispatch: {}
jobs:
  build_intel_app:
    runs-on: macos-12
    steps:
    - !<matt.mbuild.admin.ghwf.model.action.GHUseAction>
      uses: actions/setup-java@v3
      with:
        distribution: corretto
        java-version: 17
        java-package: jdk
    - !<matt.mbuild.admin.ghwf.model.action.GHUseAction>
      uses: robinraju/release-downloader@v1.7
      with:
        repository: mjgroth/deephys
        latest: true
        fileName: nn-deephys-intel-0-all.jar
    - !<matt.mbuild.admin.ghwf.model.action.GHRunAction>
      env:
        EXAMPLE_TOKEN: my-token
      run: "\t\t\t  mv nn-deephys-intel-0-all.jar input\nmkdir temp\nmkdir output\n\
        curl -LJ0 https://github.com/mjgroth/deephys/blob/4743f4adc089228c0cd1a93ab6058b0da5e711ff/src/main/resources/logo.icns\
        \ -o logo.icns\njpackage --type app-image --verbose --name deephys --app-version\
        \ 1.26.0 --main-jar nn-deephys-intel-0-all.jar --java-options \"-Dprism.maxvram=2G\"\
        \ --java-options -Xmx6144m --java-options -XX:-OmitStackTraceInFastThrow --dest\
        \ output --icon logo.icns --input input --temp temp --mac-package-identifier\
        \ lab.sinha.deephy --mac-package-signing-prefix lab.sinha.deephy --mac-sign"
  build_linux_app:
    runs-on: ubuntu-22.04
    steps:
    - !<matt.mbuild.admin.ghwf.model.action.GHUseAction>
      uses: actions/setup-java@v3
      with:
        distribution: corretto
        java-version: 17
        java-package: jdk
    - !<matt.mbuild.admin.ghwf.model.action.GHUseAction>
      uses: robinraju/release-downloader@v1.7
      with:
        repository: mjgroth/deephys
        latest: true
        fileName: nn-deephys-linux-0-all.jar
    - !<matt.mbuild.admin.ghwf.model.action.GHRunAction>
      env:
        EXAMPLE_TOKEN: my-token
      run: "\t\t\t  mv nn-deephys-linux-0-all.jar input\nmkdir temp\nmkdir output\n\
        curl -LJ0 https://github.com/mjgroth/deephys/blob/4743f4adc089228c0cd1a93ab6058b0da5e711ff/src/main/resources/logo.icns\
        \ -o logo.icns\njpackage --type app-image --verbose --name deephys --app-version\
        \ 1.26.0 --main-jar nn-deephys-linux-0-all.jar --java-options \"-Dprism.maxvram=2G\"\
        \ --java-options -Xmx6144m --java-options -XX:-OmitStackTraceInFastThrow --dest\
        \ output --icon logo.icns --input input --temp temp"
  build_windows_app:
    runs-on: windows-2022
    steps:
    - !<matt.mbuild.admin.ghwf.model.action.GHUseAction>
      uses: actions/setup-java@v3
      with:
        distribution: corretto
        java-version: 17
        java-package: jdk
    - !<matt.mbuild.admin.ghwf.model.action.GHUseAction>
      uses: robinraju/release-downloader@v1.7
      with:
        repository: mjgroth/deephys
        latest: true
        fileName: nn-deephys-windows-0-all.jar
    - !<matt.mbuild.admin.ghwf.model.action.GHRunAction>
      env:
        EXAMPLE_TOKEN: my-token
      run: "\t\t\t  mv nn-deephys-windows-0-all.jar input\nmkdir temp\nmkdir output\n\
        curl -LJ0 https://github.com/mjgroth/deephys/blob/4743f4adc089228c0cd1a93ab6058b0da5e711ff/src/main/resources/logo.icns\
        \ -o logo.icns\njpackage --type app-image --verbose --name deephys --app-version\
        \ 1.26.0 --main-jar nn-deephys-windows-0-all.jar --java-options \"-Dprism.maxvram=2G\"\
        \ --java-options -Xmx6144m --java-options -XX:-OmitStackTraceInFastThrow --dest\
        \ output --icon logo.icns --input input --temp temp"