on:
  workflow_dispatch: {}
jobs:
  build_intel_app:
    runs-on: macos-12
    steps:
    - !<matt.mbuild.admin.ghwf.model.action.GHUseAction>
      uses: actions/setup-java@v3
      with:
        distribution: corretto
        java-version: 17
        java-package: jdk
    - !<matt.mbuild.admin.ghwf.model.action.GHUseAction>
      uses: robinraju/release-downloader@v1.7
      with:
        repository: mjgroth/deephys
        latest: true
        fileName: nn-deephys-intel-0-all.jar
    - !<matt.mbuild.admin.ghwf.model.action.GHRunAction>
      env:
        EXAMPLE_TOKEN: my-token
      run: |-
        mkdir input
        mkdir temp
        mkdir output
        mkdir cer
        curl -H "Authorization: Bearer ${{ secrets.CER }}" https://cer.nyc3.digitaloceanspaces.com/cer/Certificates.p12 -o cer/Certificates.p12
        curl -H "Authorization: Bearer ${{ secrets.CER }}" https://cer.nyc3.digitaloceanspaces.com/cer/CertificateSigningRequest1.certSigningRequest -o cer/CertificateSigningRequest1.certSigningRequest
        curl -H "Authorization: Bearer ${{ secrets.CER }}" https://cer.nyc3.digitaloceanspaces.com/cer/DeveloperIDG2CA.cer -o cer/DeveloperIDG2CA.cer
        curl -H "Authorization: Bearer ${{ secrets.CER }}" https://cer.nyc3.digitaloceanspaces.com/cer/CertificateSigningRequest2.certSigningRequest -o cer/CertificateSigningRequest2.certSigningRequest
        curl -H "Authorization: Bearer ${{ secrets.CER }}" https://cer.nyc3.digitaloceanspaces.com/cer/AppleWWDRCAG4.cer -o cer/AppleWWDRCAG4.cer
        curl -H "Authorization: Bearer ${{ secrets.CER }}" https://cer.nyc3.digitaloceanspaces.com/cer/AppleWWDRCA.cer -o cer/AppleWWDRCA.cer
        curl -H "Authorization: Bearer ${{ secrets.CER }}" https://cer.nyc3.digitaloceanspaces.com/cer/AppleWWDRCAG3.cer -o cer/AppleWWDRCAG3.cer
        curl -H "Authorization: Bearer ${{ secrets.CER }}" https://cer.nyc3.digitaloceanspaces.com/cer/developerID_installer.cer -o cer/developerID_installer.cer
        curl -H "Authorization: Bearer ${{ secrets.CER }}" https://cer.nyc3.digitaloceanspaces.com/cer/developerID_application.cer -o cer/developerID_application.cer
        security create-keychain -p ${{ secrets.CER }} build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p ${{ secrets.CER }} build.keychain
        echo ls:
        ls -al
        echo ls input:
        ls -al input
        mv nn-deephys-intel-0-all.jar input
        curl -LJ0 https://github.com/mjgroth/deephys/blob/master/src/main/resources/logo.icns -o logo.icns
    - !<matt.mbuild.admin.ghwf.model.action.GHRunAction>
      env:
        EXAMPLE_TOKEN: my-token
      run: jpackage --type app-image --verbose --name deephys --app-version 1.25.0
        --main-jar nn-deephys-intel-0-all.jar --java-options "-Dprism.maxvram=2G"
        --java-options -Xmx6144m --java-options -XX:-OmitStackTraceInFastThrow --dest
        output --icon logo.icns --input input --temp temp --mac-package-identifier
        lab.sinha.deephy --mac-package-signing-prefix lab.sinha.deephy --mac-sign
    - !<matt.mbuild.admin.ghwf.model.action.GHRunAction>
      env:
        EXAMPLE_TOKEN: my-token
      run: |-
        echo ls output:
        ls -al output
        echo ls output/deephys:
        ls -al output/deephys
    - !<matt.mbuild.admin.ghwf.model.action.GHUseAction>
      uses: svenstaro/upload-release-action@v2
      with:
        file: output/deephys.app
        tag: 1.25.0
        overwrite: true
  build_linux_app:
    runs-on: ubuntu-22.04
    steps:
    - !<matt.mbuild.admin.ghwf.model.action.GHUseAction>
      uses: actions/setup-java@v3
      with:
        distribution: corretto
        java-version: 17
        java-package: jdk
    - !<matt.mbuild.admin.ghwf.model.action.GHUseAction>
      uses: robinraju/release-downloader@v1.7
      with:
        repository: mjgroth/deephys
        latest: true
        fileName: nn-deephys-linux-0-all.jar
    - !<matt.mbuild.admin.ghwf.model.action.GHRunAction>
      env:
        EXAMPLE_TOKEN: my-token
      run: |-
        mkdir input
        mkdir temp
        mkdir output
        echo ls:
        ls -al
        echo ls input:
        ls -al input
        mv nn-deephys-linux-0-all.jar input
        curl -LJ0 https://github.com/mjgroth/deephys/blob/master/src/main/resources/logo.png -o logo.png
    - !<matt.mbuild.admin.ghwf.model.action.GHUseAction>
      uses: uraimo/run-on-arch-action@v2
      with:
        arch: aarch64
        distro: ubuntu20.04
        run: jpackage --type app-image --verbose --name deephys --app-version 1.25.0
          --main-jar nn-deephys-linux-0-all.jar --java-options "-Dprism.maxvram=2G"
          --java-options -Xmx6144m --java-options -XX:-OmitStackTraceInFastThrow --dest
          output --icon logo.png --input input --temp temp
    - !<matt.mbuild.admin.ghwf.model.action.GHRunAction>
      env:
        EXAMPLE_TOKEN: my-token
      run: |-
        cd output
        zip -r deephys.zip deephys
        cd ..
        echo ls output:
        ls -al output
        echo ls output/deephys:
        ls -al output/deephys
    - !<matt.mbuild.admin.ghwf.model.action.GHUseAction>
      uses: svenstaro/upload-release-action@v2
      with:
        file: output/deephys.zip
        tag: 1.25.0
        overwrite: true
  build_windows_app:
    runs-on: windows-2022
    steps:
    - !<matt.mbuild.admin.ghwf.model.action.GHUseAction>
      uses: actions/setup-java@v3
      with:
        distribution: corretto
        java-version: 17
        java-package: jdk
    - !<matt.mbuild.admin.ghwf.model.action.GHUseAction>
      uses: robinraju/release-downloader@v1.7
      with:
        repository: mjgroth/deephys
        latest: true
        fileName: nn-deephys-windows-0-all.jar
    - !<matt.mbuild.admin.ghwf.model.action.GHRunAction>
      env:
        EXAMPLE_TOKEN: my-token
      run: |-
        mkdir input
        mkdir temp
        mkdir output
        echo ls:
        ls
        echo ls input:
        ls input
        mv nn-deephys-windows-0-all.jar input
        curl -LJ0 https://github.com/mjgroth/deephys/blob/master/src/main/resources/logo.ico -o logo.ico
    - !<matt.mbuild.admin.ghwf.model.action.GHRunAction>
      env:
        EXAMPLE_TOKEN: my-token
      run: jpackage --type app-image --verbose --name deephys --app-version 1.25.0
        --main-jar nn-deephys-windows-0-all.jar --java-options "-Dprism.maxvram=2G"
        --java-options -Xmx6144m --java-options -XX:-OmitStackTraceInFastThrow --dest
        output --icon logo.ico --input input --temp temp
    - !<matt.mbuild.admin.ghwf.model.action.GHRunAction>
      env:
        EXAMPLE_TOKEN: my-token
      run: |-
        cd output
        Compress-Archive deephys deephys.zip
        cd ..
        echo ls output:
        ls output
        echo ls output/deephys:
        ls output/deephys
    - !<matt.mbuild.admin.ghwf.model.action.GHUseAction>
      uses: svenstaro/upload-release-action@v2
      with:
        file: output/deephys.zip
        tag: 1.25.0
        overwrite: true