on:
  workflow_dispatch: {}
jobs:
  build_intel_mac_app:
    runs-on: macos-12
    steps:
    - !<matt.mbuild.admin.ghwf.model.GHUseAction>
      uses: robinraju/release-downloader@v1.7
      with:
        repository: mjgroth/deephys
        latest: true
        fileName: nn-deephys-intel-0-all.jar
    - !<matt.mbuild.admin.ghwf.model.GHRunAction>
      env:
        EXAMPLE_TOKEN: my-token
      run: |-
        echo "hello gh action 2"
        echo "hello gh action 3"
        ls
        [Ljava.io.Serializable;@7045f85a
        ls
  build_linux_app:
    runs-on: ubuntu-22.04
    steps:
    - !<matt.mbuild.admin.ghwf.model.GHUseAction>
      uses: robinraju/release-downloader@v1.7
      with:
        repository: mjgroth/deephys
        latest: true
        fileName: nn-deephys-linux-0-all.jar
    - !<matt.mbuild.admin.ghwf.model.GHRunAction>
      env:
        EXAMPLE_TOKEN: my-token
      run: |-
        echo "hello gh action 2"
        echo "hello gh action 3"
        ls
        [Ljava.io.Serializable;@21145613
  build_windows_app:
    runs-on: windows-2022
    steps:
    - !<matt.mbuild.admin.ghwf.model.GHUseAction>
      uses: robinraju/release-downloader@v1.7
      with:
        repository: mjgroth/deephys
        latest: true
        fileName: nn-deephys-windows-0-all.jar
    - !<matt.mbuild.admin.ghwf.model.GHRunAction>
      env:
        EXAMPLE_TOKEN: my-token
      run: |-
        echo "hello gh action 2"
        echo "hello gh action 3"
        ls
        [Ljava.io.Serializable;@6cc015ec